// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const { FlatCompat } = require("@eslint/eslintrc");
const expoConfig = require("eslint-config-expo/flat");
const globals = require("globals");

// `eslint-config-next` ships eslintrc-shaped configs only, so this is the
// bridge. `recommendedConfig` is required by FlatCompat even when nothing
// here extends "eslint:recommended"; an empty object is the documented stand-in.
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: {},
});

// `expo lint` only ever walks src/, app/ and components/, so the repo's other
// JavaScript — jest.setup.js, __mocks__/, plugins/, the config tests — went
// unlinted. `yarn lint` runs `eslint .` instead, which means those files need
// their environment declared: they are Node + Jest, not React Native.
module.exports = defineConfig([
  {
    // Generated by expo-router; it carries its own eslint-disable directives
    // that are unused under this config, and --max-warnings 0 fails on those.
    ignores: [
      "apps/mobile/dist/*",
      "apps/mobile/.expo/*",
      "apps/web/.next/*",
      // Written by Next itself and marked "should not be edited" in its own
      // header. Its triple-slash references are exactly what
      // `@typescript-eslint/triple-slash-reference` objects to.
      "apps/web/next-env.d.ts",
      // Istanbul's HTML report ships its own vendored JS, complete with
      // eslint-disable directives that are unused under this config.
      "**/coverage/**",
    ],
  },
  {
    // The Expo config is scoped now that the repo holds more than one app, and
    // `packages/core` rides along with it for one reason: element 7 of
    // `eslint-config-expo/flat` is the only source of a TypeScript parser here
    // (`typescript-eslint` itself is not installed, only the parser, and only
    // transitively). Without it every core `.ts` file returns
    // `Parsing error: Unexpected token {` and the boundary rule below never
    // runs — silently, which is the failure worth avoiding.
    //
    // Note this demotes expoConfig's global `ignores: ["android/app/build"]`
    // to a scoped one. Harmless while /apps/mobile/android is gitignored.
    files: [
      "apps/mobile/**/*.{js,jsx,ts,tsx}",
      "packages/core/**/*.{ts,tsx}",
    ],
    extends: [expoConfig],
    settings: {
      // `eslint-import-resolver-typescript` looks for a `tsconfig.json` beside
      // the cwd by default, and there is no longer one at the repo root — so
      // without this every `@/…` import reports `import/no-unresolved`. Both
      // resolvers have to be restated: flat config replaces `import/resolver`
      // wholesale rather than merging into what expoConfig set.
      "import/resolver": {
        typescript: { project: ["apps/mobile/tsconfig.json"] },
        node: {
          extensions: [".cjs", ".mjs", ".js", ".jsx", ".ts", ".tsx", ".d.ts"],
        },
      },
    },
  },
  {
    // The boundary, enforced rather than described. Core is compiled inside
    // each app's project, so an app-only import here would typecheck in the
    // Expo app and fail in the Next one — which is the worst possible place to
    // find out. `@/` still resolves into `packages/core` for now, so without
    // this rule a core file could reach back into `src/` and nothing would say
    // so until the fallback is dropped.
    //
    // What core is allowed to name: relative paths inside itself, real npm
    // packages, and `@brelly/platform/*` — the seams each app resolves to its
    // own implementations.
    files: ["packages/core/**/*.ts", "packages/core/**/*.tsx"],
    rules: {
      // The seams are bare specifiers no package provides — that is the whole
      // design — so the resolver cannot be expected to find them. Each app
      // maps them in its own tsconfig; drift is caught by that app's `tsc`,
      // not here.
      "import/no-unresolved": ["error", { ignore: ["^@brelly/platform/"] }],
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              // `react-native-*` is listed separately on purpose: minimatch
              // reads `react-native/*` as a path segment, so it does NOT match
              // `react-native-mmkv` — which is exactly the package this rule
              // exists to catch.
              // Every pattern is anchored with a leading slash, and that
              // is load-bearing: eslint 9 matches these with gitignore
              // semantics, where an unanchored `firebase` matches any path
              // segment called firebase — including `@brelly/platform/firebase`,
              // the seam this rule exists to send people to. `react-native-*`
              // is listed separately from `react-native/**` for the opposite
              // reason: a slash makes it a path segment, so `react-native/**`
              // does NOT match `react-native-mmkv`.
              group: [
                "/@/**",
                "/react-native",
                "/react-native/**",
                "/react-native-*",
                "/expo",
                "/expo-*",
                "/@expo/**",
                "/@bacons/**",
                "/@react-native-firebase/**",
                "/@react-native-google-signin/**",
                "/firebase",
                "/firebase/**",
                "/next",
                "/next/**",
              ],
              message:
                "packages/core is platform-free: go through @brelly/platform/* (behaviour) or configureCore() (values). If the file is in core, use a relative path.",
            },
            {
              group: ["/@brelly/core", "/@brelly/core/**"],
              message:
                "packages/core must not import itself by package name — use a relative path.",
            },
          ],
        },
      ],
    },
  },
  {
    // `eslint-config-next` is still eslintrc-shaped in Next 15 — there is no
    // `/flat` entry in the installed package — so it comes through FlatCompat
    // rather than `extends`. Scoped to this app for the same reason the Expo
    // block is scoped to its own: neither config's rules mean anything in the
    // other app's files.
    files: ["apps/web/**/*.{js,jsx,mjs,ts,tsx}"],
    // `jest.config.js` is a CommonJS Node script, like every other
    // `*.config.js` in this repo, and `next/typescript` forbids `require()`.
    // It is linted by the Node/Jest globals block at the bottom instead.
    ignores: ["apps/web/jest.config.js"],
    extends: compat.extends("next/core-web-vitals", "next/typescript"),
    settings: {
      // Same trap as the Expo block: there is no root `tsconfig.json` for
      // `eslint-import-resolver-typescript` to find beside the cwd, and flat
      // config replaces `import/resolver` wholesale rather than merging.
      "import/resolver": {
        typescript: { project: ["apps/web/tsconfig.json"] },
        node: {
          extensions: [".cjs", ".mjs", ".js", ".jsx", ".ts", ".tsx", ".d.ts"],
        },
      },
      next: { rootDir: "apps/web" },
    },
  },
  {
    // The app-facing half of the same boundary, for web. Identical to the
    // mobile block below it and deliberately not merged with it: the two apps
    // have different `files` globs and one of them may need an exception the
    // other does not.
    files: ["apps/web/src/**/*.ts", "apps/web/src/**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@brelly/core/*", "!@brelly/core/test"],
              message:
                "Import from \"@brelly/core\" — the barrel is the package's only entry point. (jest.mock may still name a module directly.)",
            },
          ],
        },
      ],
    },
  },
  {
    // The app-facing half of the same boundary. `@brelly/core` is one module;
    // a deep import is a dependency on where core keeps a file, and once one
    // exists core cannot move its own files again.
    //
    // Deliberately a rule about *imports*, which leaves `jest.mock(
    // "@brelly/core/services/weather")` alone — and that is the right line.
    // `jest.mock` names a module to replace rather than a specifier the code
    // under test used, and it has to name the real module: Jest keys its
    // registry by resolved path, so replacing the file is what intercepts one
    // core module calling another. The barrel cannot do that job, because
    // those calls never pass through it.
    files: ["apps/mobile/src/**/*.ts", "apps/mobile/src/**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              // `@brelly/core/test` is excepted because it is the package's
              // other deliberate entry point, not a path into its insides: it
              // holds the Firestore and auth fakes, which both apps' Jest
              // setup needs and neither app owns. It stays out of the barrel
              // so that test doubles never reach a bundle.
              group: ["@brelly/core/*", "!@brelly/core/test"],
              message:
                "Import from \"@brelly/core\" — the barrel is the package's only entry point. (jest.mock may still name a module directly.)",
            },
          ],
        },
      ],
    },
  },
  {
    files: [
      "apps/mobile/jest.setup.js",
      "apps/mobile/__mocks__/**/*.js",
      "**/*.test.js",
      "*.config.js",
      "apps/*/*.config.js",
      "apps/mobile/plugins/**/*.js",
      "apps/mobile/scripts/**/*.js",
      "apps/web/jest.config.js",
      // The workspace packages carry their own Jest config and setup, which
      // are Node scripts for the same reason the root's are.
      "packages/*/jest.config.js",
      "packages/*/jest.setup.js",
    ],
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
    },
  },
]);
