// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");
const globals = require("globals");

// `expo lint` only ever walks src/, app/ and components/, so the repo's other
// JavaScript — jest.setup.js, __mocks__/, plugins/, the config tests — went
// unlinted. `yarn lint` runs `eslint .` instead, which means those files need
// their environment declared: they are Node + Jest, not React Native.
module.exports = defineConfig([
  expoConfig,
  {
    // Generated by expo-router; it carries its own eslint-disable directives
    // that are unused under this config, and --max-warnings 0 fails on those.
    ignores: ["dist/*", ".expo/*"],
  },
  {
    files: [
      "jest.setup.js",
      "__mocks__/**/*.js",
      "**/*.test.js",
      "*.config.js",
      "plugins/**/*.js",
      "scripts/**/*.js",
    ],
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
    },
  },
]);
